import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./provider";
import { Toaster } from "react-hot-toast";
import '@/public/styles/flatPicker.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased font-payroll">
        <Providers>{children}</Providers>
        <Toaster position="top-center" />

      </body>
    </html>
  );
}
