import { Router } from "express";
import { displayPagibigContributionsController, displayPhilhealthContributionController, displaySSSContributionsController, displayWTaxController, updatePagibigContributionController, updatePhilhealthController, updateSSSContributionController, updateWTaxController } from "./statutory.controller";
const router = Router();
router.get("/display-sss-contributions", displaySSSContributionsController);
router.put("/sss-contributions/:id", updateSSSContributionController);
router.get("/pagibig-list", displayPagibigContributionsController);
router.put("/pagibig-edit/:id", updatePagibigContributionController);
router.get("/philhealth-list", displayPhilhealthContributionController);
router.put("/philhealth-edit/:id", updatePhilhealthController);
router.get("/display-wtax", displayWTaxController);
router.put("/wtax-edit/:id", updateWTaxController);
export default router;
